### ISSUE TITLE
New release for Perl 5.26 please

### ISSUE THREAD

**Issue by akhuettel** [ftilmann/latexdiff#104]
In Perl 5.26 (out recently) the deprecation warning about unescaped brackets becomes a fatal error.

Could we please have a new latexdiff release where that is fixed?

**Comment by ftilmann** [comment]
I just created new release (1.2.1) where hopefully the unescaped brackets are fixed. The testing is not set up to test every possible path through the programs, so it is possible that some unescaped brackets remain - I rely on community reports on this.
 (I was planning to introduce a new feature before the next release, but in the end because of the urgency of the issue you raised had to defer that to a later release)
