### ISSUE TITLE
latexdiff ignores input{}'s extension

### ISSUE THREAD

**Issue by homocomputeris** [ftilmann/latexdiff#108]
Hi,
In my TeX file I have `\input{figure.tikz}` that adds a file called `figure.tikz`, and pdfLaTeX compiles it.
However, latexdiff produces an error, ignoring the explicitly given full name:
`Couldn't open old/figure.tikz.tex: No such file or directory at /usr/bin/latexdiff line 1666`
Without `.tikz`, it searches for `figure.tex` which doesn't exist.

**Comment by ftilmann** [comment]
This error message occurs in different parts of the code, and the line number is of limited use without information on latexdiff version.  
Can I ask for clarification: do you try to process this file directly, i.e. `latexdiff figure.tikz ...` or do you use `--flatten` option of latexdiff. I don't use tikz myself, so can I ask to which extent it even makes sense to process it with latexdiff.  Is it not mostly used for producing graphics. Of course, the error message should not occur, but in the `--flatten` option would it maybe be better to leave the \input command alone rather than actually in-lining the file.

**Comment by homocomputeris** [comment]
Thanks for the answer. Sorry for having forgotten to include the version info.
```
This is LATEXDIFF 1.2.1  (Algorithm::Diff 1.15 fast, Perl v5.26.0)
  (c) 2004-2017 F J Tilmann
```
Without `--flatten` it works fine, thanks. I used this flag because it seemed to work with my filed in previous versions.
