### ISSUE TITLE
diff file cannot be compiled when difference is in the section names

### ISSUE THREAD

**Issue by foice** [ftilmann/latexdiff#129]
```
\begin{document}

\section{My Section N1}
the fox jumped the sharks

\section{My Section N2}
the sharks jumped the turtle



\end{document}
```

changed into

```
\begin{document}

\section{My renamed Section N1}
the fox jumped the sharks

\section{My other Section N2}
the sharks jumped the turtle



\end{document}
```

diffed with
`latexdiff --enforce-auto-mbox --enable-citation-markup before.tex after.tex > diff.tex` 

gives me a a dff.tex file that does not compile. is this expected? should I add more options to make it work?

I am using
```
This is LATEXDIFF 1.1.1  (Algorithm::Diff 1.15 so, Perl v5.24.1)
  (c) 2004-2015 F J Tilmann
```

**Comment by ftilmann** [comment]
I get some weirdness because of the \begin{document} right at the beginning of the file, but if I add a \documentclass statement to both, everything works out fine.

The weirdness consists of a stripping of the \begin{document} and \end{document} statements. It is strictly speaking a bug, but because this configuration is probably quite unusual I will not spend time to fix it. If you cannot add \documentclass statement, probably adding a comment line before \begin{document} will work, too.

**Comment by foice** [comment]
sorry what I meant is that you should put a {document} like that in a complete file such as what I am attaching 
[Archive.zip](https://github.com/ftilmann/latexdiff/files/1536831/Archive.zip)

does this example work for you?

**Comment by ftilmann** [comment]
Yes, indeed there is an incompatibility between the ulem package (used by latexdiff for the underlining and striking-through) and one of the embedded packages.
In this particular case I think the hyperref package might be included by one of the packages, or it's sharing code, as I could get the diff file to work by running
`latexdiff --packages=hyperref before.tex after.tex > diff.tex`

**Comment by psisquared2** [comment]
I just had the same issue and I can confirm that hyperref is the problem here. I have a minimal working example attached. The issue appears when hyperref is loaded in a different file (e.g. included via `\input`) and then you change the title of a section.

[hyperref_bug.zip](https://github.com/ftilmann/latexdiff/files/2930038/hyperref_bug.zip)

The diff file is broken if I run `latexdiff a.tex b.tex > diff.tex`, but `latexdiff --packages=hyperref a.tex b.tex > diff.tex` or `latexdiff --flatten a.tex b.tex > diff.tex` return a working diff file.

Would it be possible to automatically scan included files for "problematic" packages? Or at least issue a warning to unsuspecting users, as the origin of this problem is quite difficult to find?
