### ISSUE TITLE
Japanese characters are handled as "words"

### ISSUE THREAD

**Issue by akira-okumura** [ftilmann/latexdiff#145]
Japanese characters are well supported in the recent versions of latexdiff. Thank you very much.

But in some cases the latexidff output is different from my expectation, because a block of Japanese characters in the same character types is handled as a word. For example, the diff between "宇宙線の観測" and 宇宙線観測" should be 

    宇宙線 \DIFdelbegin \DIFdel{の}\DIFdelend 観測

but in reality latexdiff generate the following output.

    \DIFdelbegin \DIFdel{宇宙線の観測}\DIFdelend \DIFaddbegin \DIFadd{宇宙線観測}\DIFaddend
 
So the PDF output looks to be very redundant and thus it is difficult for the reader to see what were actually removed or added.
<img width="672" alt="screen shot 2018-02-27 at 11 34 14" src="https://user-images.githubusercontent.com/2981330/36708215-5a2fd022-1bb5-11e8-8f5d-3e018cbac7fc.png">

If you need help from Japanese contributors, you can send the following message to them.

----

漢字や平仮名の集合といったものが単語のように扱われるためか、文章によっては意図しない出力結果を得ることがあります。例えば「宇宙線の観測」と「宇宙線観測」では、

    宇宙線 \DIFdelbegin \DIFdel{の}\DIFdelend 観測

となるべきだと思いますが、実際には

    \DIFdelbegin \DIFdel{宇宙線の観測}\DIFdelend \DIFaddbegin \DIFadd{宇宙線観測}\DIFaddend

となり、冗長な出力になります。そのため、実際に何が挿入、削除されたのかの理解が困難になります。
<img width="672" alt="screen shot 2018-02-27 at 11 34 14" src="https://user-images.githubusercontent.com/2981330/36708215-5a2fd022-1bb5-11e8-8f5d-3e018cbac7fc.png">

**Comment by ftilmann** [comment]
Hi I am glad to know that latexdiff is working with Japanese.  Nothing to do with me really, it is the magic of Perl's pattern matching, which is also where the 'problem' lies.  I will indeed need some support to address your request.
Do you know how the Japanese symbols are encoded in your text (UTF-8, UTF-16)?   Would you be happy with all Japanese symbols being treated as 'words', i.e., the change detection working on symbol level?  If so, the fix could be relatively easy, as latexdiff would simply have to treat Japanese signs identically to the way it now treats interpunctation signs.  So then it would just be necessary what is the Perl code for Japanese characters - if you know it, please let me know, otherwise it must be possible to find this out. 
At a minimum you should provide me with example files (old and new text), as otherwise I would not even know where to start.
I should warn that even if you do your homework of providing these, it might take me considerable time to actually implement this, as latexdiff is only a hobby, and there are some other feature and pull requests that I need to attend.

**Comment by ftilmann** [comment]
If you know Perl you could attempt a fix yourself - somewhere around these lines
```
  my $quotemarks = '(?:\'\')|(?:\`\`)';
  my $punct='[0.,\/\'\`:;\"\?\(\)\[\]!~\p{IsNonAsciiPunct}\p{IsNonAsciiS}]';
  my $number='-?\d*\.\d*';
```
If you extend the set of characters under `my $punct ` by Japanese characters (or define a separate category to be used later), you should be able to achieve your objective.

**Comment by akira-okumura** [comment]
Hi @ftilmann,

Thank you for your replies.

> Do you know how the Japanese symbols are encoded in your text (UTF-8, UTF-16)?

I usually use utf-8-unix with Emacs, but many Windows users still use Shift JIS with CR-LF.

> Would you be happy with all Japanese symbols being treated as 'words', i.e., the change detection working on symbol level?

Perhaps some people complain if latexdiff always treats individual Japanese characters as words. For example, one of the meanings of "でも" is "but" while "で" means "at" or "by," and "も" means "also" or "too." Therefore, some people want to have "でも" be processed as a single word but some do not.

I think the best way is to have an option with which Japanese users can choose the behavior.

I am not a Perl user but I will look into the code.

I will attache two files for your test.

[new.txt](https://github.com/ftilmann/latexdiff/files/1809955/new.txt)
[old.txt](https://github.com/ftilmann/latexdiff/files/1809956/old.txt)
