### ISSUE TITLE
Underscores in ``\includegraphics`` filename breaks ``pdflatex`` output

### ISSUE THREAD

**Issue by victor-gonzalez** [ftilmann/latexdiff#148]
I know this is a tricky example but, with long and meaningful filenames, it happens

The original file
```
\documentclass[11pt]{article}
\usepackage{graphicx}

\begin{document}

\begin{figure}
    \centering
    \includegraphics[scale=0.35,keepaspectratio=true,clip=true,trim=5pt 4pt 3pt 2pt]
    {my_a_fig}
    \caption{\label{fig:a}Figure A}
\end{figure}

\end{document}
```
I needed to modify the trimming on the left side so, the modified file
```
\documentclass[11pt]{article}
\usepackage{graphicx}

\begin{document}

\begin{figure}
    \centering
    \includegraphics[scale=0.35,keepaspectratio=true,clip=true,trim=100pt 4pt 3pt 2pt]
    {my_a_fig}
    \caption{\label{fig:a}Figure A}
\end{figure}

\end{document} 
```
and the output of ``latexdiff`` for the involved lines
```
\begin{figure}
    \centering
    \DIFdelbeginFL %DIFDELCMD < \includegraphics[scale=0.35,keepaspectratio=true,clip=true,trim=5pt 4pt 3pt 2pt]
%DIFDELCMD <     %%%
\DIFdelendFL \DIFaddbeginFL \includegraphics[scale=0.35,keepaspectratio=true,clip=true,trim=100pt 4pt 3pt 2pt]
    \DIFaddendFL {my_a_fig}
    \caption{\label{fig:a}Figure A}
\end{figure}
```
which breaks ``pdflatex`` due to the isolated underscores.

If the filename is in the same line as the ``\includegraphics``, as in
```
    \includegraphics[scale=0.35,keepaspectratio=true,clip=true,trim=100pt 4pt 3pt 2pt]{my_a_fig}
```
then everything goes fine. But in most of the cases two lines are needed due to long filenames and paths.

As having them in a single line does actually work, a potential fix would be to flatten ``\includegraphs`` to a single line before processing it. But I don't know how much complex is to have them in that shape.

Thanks for a great utility!
Cheers,
Víctor.

**Comment by ftilmann** [comment]
The need to have all arguments follow the command without spaces (and all having to be surrounded by curly braces) is a documented limitation of latexdiff. Otherwise latexdiff would have to know how many arguments each command is expecting - to my knowledge there is no simple way to know this. 
It's subjective, of course, but I also don't really find your argument compelling for having to put the filename in a long line - sure, it will make a long line, but any decent editor will wrap it for display. 

In any case, option `--allow-spaces` should solve your problem. Although I haven't tested it with newlines, I think it should work. There might be some unwanted side effects, though. Let me know if this fixes your problem and close the issue if it does.

**Comment by victor-gonzalez** [comment]
Yes! ``--allow-spaces`` solved it, not only for the MWE but also for other much more complex documents. And no side effects, so far!

Thanks!
