### ISSUE TITLE
diff results in a lot of overfull boxes

### ISSUE THREAD

**Issue by EDiLD** [ftilmann/latexdiff#16]
Hai @developers of latexdiff.

I am currently revising a scientific manuscript for submission to a journal [(git-repo)](https://github.com/EDiLD/usetheglm).
However, latexdiff result in a lot (and ugly) overfull boxes, see [diff.pdf](https://github.com/EDiLD/usetheglm/blob/master/manuscript/revision/diff/diff.pdf).

Any ideas how to make this better looking? I think allowing more linebreaks would solve many issues...

The original manuscript can be found here: [tex](https://github.com/EDiLD/usetheglm/blob/master/manuscript/submission/report/report.tex), [pdf](https://github.com/EDiLD/usetheglm/blob/master/manuscript/submission/report/report.pdf)
The revised one here: [tex](https://github.com/EDiLD/usetheglm/blob/master/manuscript/revision/report/report.tex), [pdf](https://github.com/EDiLD/usetheglm/blob/master/manuscript/revision/report/report.pdf)
The svjour class, .bst and .bib files are in the topfolder as the .tex files (perhabs just clone / download the whole repo for testing).

I am using the follwing command to create the diff:
```
$latexdiff --version
This is LATEXDIFF 1.0.4  (Algorithm::Diff 1.15 so, Perl v5.18.2)
  (c) 2004-2014 F J Tilmann

$latexdiff --disable-citation-markup --math-markup=3 submission/report/report.tex revision/report/report.tex > revision/diff/diff.tex
```

The linebreaks are also one of the reasons why I disabled markup for citations. Moreover, how can I mark changes to the title/subtitle?

Thanks for your work on this very helpful piece of software!

**Comment by EDiLD** [comment]
Ok, found solution:
added `\sloppy` to the revised MS

**Comment by ftilmann** [comment]
Another possibility is to use -t CFONT  but the markup style is maybe less intuitive so that I actually prefer your solution. 
This problem arises due to incompatibility between ulem package (used for wavy unerline and strike-out and natbib (and other citation packages), so there is not much I can do on latexdiff side.

For your title problem:(next time I recommend opening a separate issue for essentially unrelated question) 
Changes in \title should be marked up automatically. To force the same behaviour for \subtitle use
``--append-context2cmd=subtitle``  
(this is an undocumented side-effect of context2 commands).

**Comment by Nicholaswogan** [comment]
Any other tips on how to avoid overfull boxes? The `\sloppy` command doesn't work for me.

**Comment by LinqLover** [comment]
Confirm that `\sloppy` works for me. However, this will downgrade the quality of typesetting, and using it for the entire document is thus generally disrecommended. For example, there will be more and inequal whitespace in fully justified paragraphs when using `\sloppy`, and small ovefull hboxes will be silenced without being fixed. See https://tex.stackexchange.com/a/409810/221054 and https://tex.stackexchange.com/a/241355/221054 for more details.

It must be noted that using `\sloppy` is only a workaround. This bug originates from a limitation of `ulem` (used by `latexdiff`) regarding typesetting: https://tex.stackexchange.com/a/594498/221054 I have spent too much many hours trying to work with `soul` or `soulpos` instead of `ulem`. While they indeed resolve the typesetting impairment of `ulem`, they cannot be used with arbitrary commands inside the underlined/struck-out text. One possible solution would be to wrap any (!) other command into an `\mbox` (like `latexdiff` already does for `\cite`), but this would impair word-wrapping again. Another solution would be splitting up the contents of each underline/struck-out part to ensure the soul command is always the innermost, but this cannot be applied by `latexdiff` to arbitrary arguments with unlimited complexity. See https://github.com/jbezos/soulpos/issues/6, https://tex.stackexchange.com/a/652339/221054, https://tex.stackexchange.com/a/284304/221054, or https://tex.stackexchange.com/a/437779/221054 for some examples. In general, proper underlining is said to be a general limitation of TeX, and I read the recommendation to use LuaLaTeX instead multiple times. Unfortunately, that is not fully compatible with normal TeX (e.g., for fonts), so not usable as a drop-in replacement.

So in the end, no idea how this situation could be improved from here. I suppose the most promising option would be to add LuaLaTeX support to this tool through a command line argument and then use something better than ulem as shown in the examples linked above. However, I don't know for how many users this will work, I haven't tried to migrate myself.

**Comment by ftilmann** [comment]
@LinqLover Have a look at PR  #299 which implements the solution with lualatex that you suggested. It was merged a couple of days ago (not yet in a release, will be 1.3.4+). I have not had a chance to test this, as I am behind in my lualatex version.

**Comment by LinqLover** [comment]
@ftilmann Wow, this is just what I would have needed! I will definitely check out this option for my next revision. Thanks for maintaining this great tool! :-)
