### ISSUE TITLE
ONLYCHANGEDPAGE emits the wrong page on longtable s

### ISSUE THREAD

**Issue by yfarjoun** [ftilmann/latexdiff#169]
I've included latexdiff-vc in a project with continuous integration...thanks for your work on this!!!

In case you want to see it in action: https://github.com/samtools/hts-specs in particular, you can look at this recently merged PR: https://github.com/samtools/hts-specs/pull/328. the "bot" comments contain links to files generated with latexdiff-vc.

Here's my issue:

In the presence of a difference in a longtable that spans multiple pages, asking latexdiff-vc to emit only the changed pages results in only the first page, even if the difference is on the second page. 

Using the included files, I ran 
```bash
latexdiff-vc  --pdf --subtype ONLYCHANGEDPAGE  --graphics-markup=none test_table.tex test_table2.tex
```
As you can see only the first page is emitted, but the difference is in the second page.

[example.tar.gz](https://github.com/ftilmann/latexdiff/files/3005619/example.tar.gz)

Omitting the `--subtype ONLYCHANGEDPAGE` shows the difference on the second page.

**Comment by jmarshall** [comment]
It appears to have picked the wrong page on the `tabular` here too: https://github.com/samtools/hts-specs/pull/398#commitcomment-32968930 — the actual changes are page 7.

**Comment by ftilmann** [comment]
This is a known weakness of ONLYCHANGEDPAGE. From the manual 
`ONLYCHANGEDPAGE ... also highlights changed pages, without the need for post-processing, but might not work reliably if there is floating material (figures, tables).`
The longtable is not exactly floating material but has presumably a similar issue of first being internally processed before then being rendered in one go. 

Have you tried latexdiff-vc option `--only-changes`, which uses the ZLABEL style for achieving the same outcome but needs post-processing (done automatically by latexdiff-vc, but I am not sure it suits your workflow).
 I am not sure if it will work for your issue, though. If it doesn't then I am afraid this bug will be very hard to fix as it would essentially require getting into the longtable.  
A clumsy work-around could possibly be constructed by some post-processing if a ZLABEL markup is found within a long table to artificially add additional labels at the beginning and end of the table (this would imply that always the whole longtable would be shown whenever there is any change in it). Because of its clumsiness I am note sure this is a good idea, though, and probably wouldn't be a priority).

Anyway, maybe you are lucky and the --only-changes / ZLABEL approach already works.

**Comment by yfarjoun** [comment]
Thanks for the thoughful response. I'll try out --only-changes

**Comment by yfarjoun** [comment]
at first glance it seems to be working. did require an upgrade of gs (9.19 wasn't good enough) but after that hiccup it started chopping the results to the right pages. 

Thanks again!
