### ISSUE TITLE
changebar also with the pdftex option?

### ISSUE THREAD

**Issue by ouboub** [ftilmann/latexdiff#209]
Hi

I think nowadays people tend to use more pdflatex than vanilla latex (this is at least my impression from discussions in the auctex mailing list)
That is why I would like to suggest:
could latex also provide the changebar package with the pdftex option instead of the 
dvips option?
regards
Uwe Brauer

**Comment by ftilmann** [comment]
This functionality more or less exists already, just use `--driver=pdftex` option (this option as an effect only on the changebar styles. You are probably right that pdftex would nowadays be a more appropriate default; for myself it is certainly true that pdflatex is the usual choice (I can't even remember the last time I used plain latex as part of my general work). On the other hand I am normally a stickler for backwards compatibility, although in this case the number of affected users should be very small, and the fix for them is trivial

**Comment by ouboub** [comment]
> This functionality more or less exists already, just use `--driver=pdftex` option (this option as an effect only on the changebar styles. You are probably right that pdftex would nowadays be a more appropriate default; for myself it is certainly true that pdflatex is the usual choice (I can't even remember the last time I used plain latex as part of my general work). On the other hand I am normally a stickler for backwards compatibility, although in this case the number of affected users should be very small, and the fix for them is trivial

Ok. I admit I was not aware of this driver option, although I thought I scanned the man pages.

**Comment by ftilmann** [comment]
I have to confess that I put this option in the man pages but not the help text shown with `-h` option. So thanks for this report, which prompted me to fix this (and I also changed the default to pdftex now).
