### ISSUE TITLE
Versioned release archives

### ISSUE THREAD

**Issue by ryandesign** [ftilmann/latexdiff#21]
Can you please release archives that contain the version number? For example, latexdiff-1.1.0.zip?

I know you consider CTAN to be the canonical distribution site. If CTAN cannot accommodate versioned files, could you release your files on github's releases service instead, since I know they do accommodate that?

Not having the version number in the release filename causes problems every time you release a new version, e.g. https://trac.macports.org/ticket/47519.

**Comment by ftilmann** [comment]
Since recently I am marking releases with github release tags now; github prepares zip files for these. These mark the same points in time as the CTAN releases of the same name but are not the same as there are some additional tasks carried out for preparation of the release version ('Official' CTAN release is created by executing "make distribution; make release" in the git root - it will create latexdiff-so and latexdiff-fast from the top-level latexdiff and creates the documentation pdf out of various PODs (in-file perl documentation) and tex files; make release actually creates a named latexdiff-1.x.x.tgz file which I then upload to CTAN). The github also contains a suite of test files and testing script irrelevant to users. Additionally and maybe confusingly, the github-generated release zips will contain all the previous releases as sub-directories. 
Future versions will be tagged in the same way. If I started today, I might have designed the release pathway a little differently but I am reluctant to change from CTAN as the Canonical archive and want to continue to offer ready-to-use releases (i.e. preassembled documentation and latexdiff variants).  
So my question:
- does the availability of 'tagged releases' on github already fix your problem (you would be free to ignore the CTAN releases, but would have to prepare the 'user-friendly' files for the macports repo yourself)?

What do you (and others) think about the possible two changes? 
1. take out the subdirectories latexdiff-1.x.x from the version management, as these are all derived files, and so strictly speaking should not be archived
2. include the release file latexdiff-1.x.x.tgz into the repository. I currently leave this out as it is trivially derived from the corresponding sub-directory

**Comment by ryandesign** [comment]
The tagged releases do not currently meet my needs because
 1. you have subdirectories for every released version in the repository, which means that the github-generated tarballs for any tag include the source for every preceding version, making the tarballs many times the size they should be, and
 2. the auto-generated tarballs were not created with `make distribution; make release` as you said.

I recommend you remove the latexdiff-* directories from the repository. Users who want prior releases should use the tags.

You should not include tgz files in the repository either; they don't belong there. You should instead upload them to github's releases system, attached to each tag.

**Comment by ftilmann** [comment]
On your first point (taking the releases out of the repo) that makes sense to me, and I was considering this move anyway.
However, it is still not clear to me how I can make releases that are derived from the content of the repo rather than effectively being the repo, i.e. how do I "upload [the tgz files] to github's releases system" without making them part of the repo.
I had a very quick read through
https://developer.github.com/v3/repos/releases/#create-a-release
but this all seems to talk about making the whole repo a release.
I am still new to git/github with limited time to become proficient anytime soon, so if you could paste me the commands, by which such an uploaded tgz could be attached, that would be very helpful and I could try to release over two channels (i.e. through CTAN and github).

**Comment by ryandesign** [comment]
I don't have any of my own software hosted on github yet so I haven't published any releases myself, I've only used releases published in other projects. But I believe what you need to know is here:

https://github.com/blog/1547-release-your-software

**Comment by ftilmann** [comment]
Sorry for taking long to reply.  So from the document it seems possible after all to attach the compressed release tar balls as binary.  From 1.1.1 onwards I will do this in addition to the usual upload to CTAN. I hope this will avoid the checksum problems you have been having.

**Comment by ftilmann** [comment]
Version 1.1.1 now has an extra tarball latexdiff-1.1.1.tar.gz attached, which contains the processed 'release version' of latexdiff. 
Also, no new latexdiff-1.1.1 subdirectory has been included this time into the github as this is auto-generated.
I left the legacy latexdiff-1.0.x and latexdiff-1.1.0 subdirectories for now but might eventually remove them.
