### ISSUE TITLE
latexdiff introduces errors

### ISSUE THREAD

**Issue by kirk86** [ftilmann/latexdiff#266]
Hi, thanks for the `latexdiff` package.

I have two issues which could be due to me being a novice user.

1. `latexdiff` doesn't seem to work on large latex projects where I would mostly need it. For instance, a typical large latex project would involve having a main/master tex file which includes additional tex files. If I use `latexdiff` to compare the main tex files then it will ignore all the `included` tex files from the `main` file forcing the user to manually compare each tex file separately.
2. Even after manually applying `latexdiff` on each tex file separately when I try to compile the tex project seems impossible since there are a ton of errors introduced by `latexdiff` and the project won't compile, but without `latexdiff` the project compiles fine without any errors or warnings.

**Comment by ftilmann** [comment]
To 1. Have you seen the `--flatten` option. Depending on the exact way you include files, this might solve your problem. The best way to use this option is to use version control with git, svn or mercurial and then use latexdiff-vc.  While the computational demands grow superlinearly with document length I have successfully processed whole PhD thesis of > 100 pages, although the delay is noticeable (I can't quite remember but it was more than a minute I think - this will also depend strongly on the the number and distribution of changes).  

To 2. With this information it is impossible to diagnose what the problem is. In general: latexdiff is 'just' a pattern matcher making some assumptions, and there are a small number of requirements regarding the formatting (see the documentation). It does not play with all optional packages.
If you still run into a problem you need to construct an MWE (minimum working example) sharing the input files and error messages obtained as well as latexdiff version. See https://minimalbeispiel.de/mini-en.html

**Comment by ftilmann** [comment]
Close due to inactivity after requesting information
