### ISSUE TITLE
Does not work when a bibliography is present?

### ISSUE THREAD

**Issue by diego898** [ftilmann/latexdiff#28]
When I check in the following file to my git repo:
`text.tex`:
```
\documentclass[journal]{IEEEtran}
\usepackage{cite}
\begin{document}

\title{TEST TITLE}

\maketitle

\begin{abstract}
test abstract 
\end{abstract}

\begin{IEEEkeywords}
test keyword
\end{IEEEkeywords}


\section{Introduction}
etc

\end{document}
```

and then trivially modify the file an use latexdiff as: `latexdiff-vc --flatten -r HEAD test.tex` I get a diff file that compiles and is fine. 

If I start over adding the following bibliography to `test.tex`:
```
\section{Introduction}
etc \cite{sdf}

\bibliographystyle{IEEEtran}
\bibliography{testbib}
```

where `testbib.bib` is:
```
@ARTICLE{sdf,
  author = {sad},
  title = {sd},
  journal = {asd},
  year = {sdf}
}
```
then I check both in to my git repo and trivially modify `test.tex` I get the following error:
```
tes git:(master) ✗ latexdiff-vc --flatten -r HEAD test.tex
Guess you are using GIT ...
Working on  test.tex
Checking out old dir into: /var/folders/mh/f311201s7p1dvk5sp293lmh40000gn/T/F_BlbH_zU3/latexdiff-vc-HEAD (rev: HEAD)
OK to overwrite existing file test-diffHEAD.tex (y/n)? y
Running latexdiff

WARNING: Inconsistency in length of input string and parsed string:
     This often indicates faulty or non-standard latex code.
     In many cases you can ignore this and the following warning messages.
 Note that character numbers in the following are counted beginning after \begin{document} and are only approximate.
mmand{\url}[1]{#1} \csname url@samestyle\endcsname \providecommand{\ne
                              ^^^^^^^^^^
Missing characters near word 26 character index: 357-367 Length: 9 Match: |samestyle| (expected match marked above).

WARNING: Inconsistency in length of input string and parsed string:
     This often indicates faulty or non-standard latex code.
     In many cases you can ignore this and the following warning messages.
 Note that character numbers in the following are counted beginning after \begin{document} and are only approximate.
mmand{\url}[1]{#1} \csname url@samestyle\endcsname \providecommand{\ne
                              ^^^^^^^^^^
Missing characters near word 6 character index: 152-162 Length: 9 Match: |samestyle| (expected match marked above).
Generated difference file test-diffHEAD.tex
```

The generated `test-diffHEAD.tex` file does **not** compile and puts out a bunch of errors

**Comment by ftilmann** [comment]
I cannot reproduce this. I get similar warning messages but the resulting file does compile. Maybe the "trivial change" is actually causing the problems?
The warning messages are caused by the "@" symbol but can normally be ignored. 
Have you included the .bbl file in the git repository?  Otherwise the --flatten will not work properly.
Feel free to post/link old and new .tex and .bbl files as well as the diff file you are obtaining (most conveniently as a tar file rather than by pasting in comment), and I can have another look.

**Comment by diego898** [comment]
@ftilmann, I think you're right about the .bbl file. On a might-be-related note, I have made substantitive changes to a manuscript, including rearranging sections, text, and math equations. I greatly reduce the number of errors in compiling the diff file if I pass `---math-markup=0`, but I still seem to get errors related to the movement/renaming of sections. Is this a normal problem for latexdiff? Can it only handle relatively smaller types of changes? Thanks!

**Comment by ftilmann** [comment]
It should still work even for more extensive changes, although if there are a lot of moved sections, the markup might cease to be useful (as movement will appear as addition and deletion of the moved section).
Depending on which packages you use and how they redefine commands, certain constructions can cause problems, and I guess with more extensive changes the likelyhood increases you are hit by one of these. 
Sometimes the underlining causes problems and using `-t CFONT` option helps. Feel free to open another issue but I would ask you to try and isolate the problems rather than submitting a long document "that does not work".  The overall length and frequency of changes should have no bearing on whether latexdiff works (unless you hit memory limitations).
