### ISSUE TITLE
Citation undefined, possibly because bib file is a symbolic link

### ISSUE THREAD

**Issue by felixvuo** [ftilmann/latexdiff#292]
I'm using `git latexdiff --latexmk --main my-dissertation.tex first-submission-tag HEAD` to keep track of my dissertation corrections after my viva. It's working really well (I'm so grateful for this tool), but I have one problem: all the citations cannot be found, e.g.

```
Citation 'smithSeminalWork2021' on page 13 undefined on input line 1234.
```
I think this might be because my references.bib is actually a symbolic link to ../literature/zotero_library.bib. I used Zotero as my reference manager with "Better BibTeX" auto-export. The ../literature directory is also in the same github repository so has been version-controlled throughout my thesis writing.

Is there any kind of workaround, e.g. for latexdiff to treat the symlink references.bib as untracked? I saw the --ln-untracked option but my symlink is under git control.

**Comment by ftilmann** [comment]
git-latexdiff is a third party wrapper https://gitlab.com/git-latexdiff/git-latexdiff and from your problem description I think the problem is with that rather than with latexdiff itself. I cannot provide advice or fix problems with git-latexdiff so you should submit your issue there. If it turns out that there is an issue with latexdiff (or latexdiff-vc/latexdiff-git) then open another issue and construct the bug report and example without making use of git-latexdiff (in this case unlikely as latexdiff does not deal with bib files at all and only uses the generated .bbl files (with option --flatten).

**Comment by felixvuo** [comment]
I see, thank you @ftilmann for clarifying.
