### ISSUE TITLE
RED and BLUE colors are not being used

### ISSUE THREAD

**Issue by lmendo** [ftilmann/latexdiff#307]
The beginning lines of the generated diff `tex` file contain

    \RequirePackage{color}\definecolor{RED}{rgb}{1,0,0}\definecolor{BLUE}{rgb}{0,0,1} %DIF PREAMBLE
    \providecommand{\DIFaddtex}[1]{{\protect\color{blue}\uwave{#1}}} %DIF PREAMBLE
    \providecommand{\DIFdeltex}[1]{{\protect\color{red}\sout{#1}}}                      %DIF PREAMBLE

`RED` and `BLUE` are defined but not used. I think the `\DIFaddtex` and `\DIFdeltex` definitions should use those colors, so that changing the color definitions will have an effect.

**Comment by ftilmann** [comment]
Those definitions with the capital letters RED and BLUE are included because one package (I have forgotten which one) was changing all letters to capitals when moving parts of text, e.g., section or figure titles into table of contents/figures, including argument of \color. Adding the definitions for the capitalised version was an easy hack to allow mark-up in captions/section titles nonetheless.  If you like to use different colours you can change \DIFadd and \DIFdel (+tex if required) directly.
