### ISSUE TITLE
Multicolumn table breaks when number of columns changes

### ISSUE THREAD

**Issue by therussianjig** [ftilmann/latexdiff#35]
I have a large document that contains tables with footers. I am using the multicolumn command to do footers.

If the number of columns changes, the diff adds tags around the column command as shown in the attached documents.

I stripped the document down to a dummy table that shows the issues. 

This was found on Version 1.1.0

[latexDiffBugs.zip](https://github.com/ftilmann/latexdiff/files/51292/latexDiffBugs.zip)

**Comment by ftilmann** [comment]
There was a typo in your example (second argument of \multicolumn commands was "1" (the digit) instead of "l" (the letter) ).  
Also, as per latexdiff specification, latexdiff by default assumes no space between a command and its arguments but there is a space after \multicolumn. 
After fixing both issues, the diff'ed version compiles fine. If you like to retain the space it also works with `--allow-spaces` option. I hope this solves your problem.

**Comment by therussianjig** [comment]
Thanks! That worked, sorry for the mistake.
