### ISSUE TITLE
latexdiff-vc has no --config option

### ISSUE THREAD

**Issue by fkbreitl** [ftilmann/latexdiff#58]
It would be nice to have the --config option also in latexdiff-vc.

It would be convenient in such a situation:

https://tex.stackexchange.com/questions/73224/is-there-an-option-in-latexdiff-to-ignore-whole-environments/73649?noredirect=1#comment804353_73649

**Comment by ftilmann** [comment]
latexdiff-vc is supposed to pass through to latexdiff all the options it does not use but having said that in the past it gets confused what is option and what is file, and what is argument to -r. Can you post the exact string used, ideally post MWE (minimum working examples) tex files to go along with it and run latexdiff-vc in the pdf generation mode (rather than using the versioning control). If the latter is not possible, just posting the exact command line might be enough to diagnose.

**Comment by fkbreitl** [comment]
The following fails as follows:

```
latexdiff-svn --config="PICTUREENV=(?:picture|figure|DIFnomarkup|SCfigure|align)[\w\d*@]*" --force --exclude-textcmd="chapter,section,subsection,makebox" -r 134 introduction/introduction.tex
Working on  introduction/introduction.tex 
patching file introduction/introduction-oldtmp-24307.tex (read from introduction/introduction.tex)
Running latexdiff
sh: 1: Syntax error: "(" unexpected
Something went wrong in latexdiff. Deleting introduction/introduction-diff134.tex and abort

```
It is independent of the TEX file and seems to be a parsing error of latexdiff-cv.

**Comment by ftilmann** [comment]
Ok, this happens because the latexdiff-vc processing strips the quotation marks, and then executes latexdiff through a shell, which then interprets all the funny characters in the PICTUREENV definition. No easy solution just two work-arounds:
1. Use a config file instead (as per the stack exchange answer linked to in your issue opening statement)
2. Use another level of quotation marks around the whole command:
```
latexdiff-svn '--config="PICTUREENV=(?:picture|figure|DIFnomarkup|SCfigure|align)[\w\d*@]*"' ...
```
worked for me

**Comment by fkbreitl** [comment]
Ok, good to know about the problem and the workaround. Thanks!
However, since the problem is not fixed nor mentioned in the documentation the bug should not be closed. I am not saying that it has high priority but it should be kept on the todo list since a correct passing should be possible.

**Comment by ftilmann** [comment]
I was thinking the same after having slept over it.  I have modified latexdiff-vc now, so that options are wrapped in quotation marks internally. So the workaround is no longer necessary, and in fact the second one will probably break now ( commit 03b3c5d ).  With this I think it is properly closed

**Comment by fkbreitl** [comment]
Excellent! Great job! Thanks! The user will appreciate this.

**Comment by gaulinmp** [comment]
This seems to create a bug when no options are passed in (the command run is then `latexdiff '' "file1.tex"...`, and those single quotes makes problems). 

I'm new to Perl, but this seemed to fix said bug:

```
456   # Remaining options are passed to latexdiff
457   if (scalar(@ldoptions) > 0 ) {
458     $options = "\'" . join("\' \'",@ldoptions) . "\'";
459   } else {
460     $options = "";
461   }
```

**Comment by ftilmann** [comment]
Thanks for that. As you see I have just merged this
