### ISSUE TITLE
Enhancement: option to only include additions 

### ISSUE THREAD

**Issue by tdegeus** [ftilmann/latexdiff#66]
I most frequently only want to highlight the changed parts of the text, but am not so much interested in including the removals. Currently I set in the preamble

```latex
\providecommand{\DIFdel}[1]{{}}
```

This largely gives me what I want. However, I have noticed that I sometimes get some layout issues from the LaTeX-code that is generated to include the removals (for example in ``itemize``, or when a complete section has been removed). In those cases the only solution appears to manually remove the obsolete LaTeX-code that corresponds to the removed text. 

To avoid this I would really appreciate a command-line option for ``latexdiff`` (e.g. ``--add-only``) such that no LaTeX-code is generated with the deleted text.

**Comment by tdegeus** [comment]
@ftilmann I'm still very much interested in this. Often, for example in submitting a revision of a manuscript, I'm only interested in highlighting where changes were made. 

If you give me some pointers I could try prepare a PR.

**Comment by ftilmann** [comment]
Sorry for not replying earlier. I realise your original post is now nearly 3 years ago. 
The conceptually easiest approach would be doing some post-processing (in sub postprocess) and simply deleting everything between matching \DIFdelbegin and \DIFdelend markers. 
(early in the post-processing sequence so that all the other trickery has not yet been applied). It is possible that this would cause some undesirable side effects (if you prepare a PR please check your submission with the provides test suites (see instructions on the project Wiki page).

The actual marking up is done in the subroutine marktags.  So the other approach would be to modify this subroutine to detect that deleted material is supposed to be added, and simply skip it, or to suppress the calls to marktags for deleted material.  

Although somehow less elegant, I would favour the first approach because marktags is quite difficult to understand in the first place, and adding more if-clauses won't help, whereas the post-processing is essentially a linear set of pattern replacements.
