### ISSUE TITLE
Support for tabu

### ISSUE THREAD

**Issue by apYdr6uxv** [ftilmann/latexdiff#7]
Any chance to develop support for the [tabu](http://www.ctan.org/pkg/tabu) package?
The environments I had problems with were:
* `tabu`
* `longtabu`

The kind of problems were:
* diff ran on the `to \linewidth` portion of the environment declaration, catching the `to` and trying to show it off
* diff ran on the column specification portion of the environment declaration, catching the `X`es or 
anything else added to them e.g. `X[.3]`, `X[l]`
* I ran into a lack of `\\` in the headers but I couldn't make it clear to me, so I only include it here if it's easy to spot/makes sense when considering the code

My tabu example:
```latex
\begin{tabu} to \linewidth { X X[c] | X | l l r r}

\toprule
H1 & H2 & H3 & H4 & H5 & H6 & H7 \\
\midrule
\endfirsthead

\midrule
H1 & H2 & H3 & H4 & H5 & H6 & H7 \\
\midrule
\endhead

c1 & c2 & c3 & c4 & c5 & c6 & c7 \\
\bottomrule

\end{tabu}
```

**Comment by ftilmann** [comment]
A minimum working example of old, new, diff and (if not obvious) 
expected diff would be helpful. As tabu uses non-standard syntax it will 
be quite hard to adapt latexdiff.  I recommend using PICTUREENV 
configuration variable to disable highlighting within tabu environment

**Comment by apYdr6uxv** [comment]
Here's an example of what happens.
Nothing in this code should actually have a `\DIFadd`.
```latex
\begin{longtabu} \DIFadd{to }\linewidth { \DIFadd{X}[\DIFadd{-1}] \DIFadd{X}[\DIFadd{.95}] \DIFadd{X}[\DIFadd{1.3}] \DIFadd{X}[\DIFadd{2}]}
```

Using `PICTUREENV` is undesirable because the table content highlighting works fine .

**Comment by ftilmann** [comment]
I see what you mean now - the trouble arises because the longtabu environment seems to have a very unusual syntax, with bare words (in this case 'to') being interpreted - latexdiff expects arguments of environments or commands to be directly adjacent to them (no spaces, this is the one generic syntax condition above standard latex latexdiff imposes - see latexdiff documentation for more details). As it will be a losing battle trying to make latexdiff compatible with every exotic package I will only fix this if I see this is an issue for others, too, i.e. if I get more reports on this topic (feel free to add 'me too' messages in this thread, if you like to see this fixed)

**Comment by ftilmann** [comment]
No further feedback received on this so I will close it for now. You can try simply removing the space between \linewidth and the following argument, and use a post-processing script to get rid of the markup for "to"

**Comment by alimuldal** [comment]
FWIW I just got bitten by the same issue

**Comment by paul-pearce** [comment]
I'm running into this. I'm not using tabu, just tabular. It seems like the IEEE style file is interacting with tabular in some way to bring out this bug (and in general is making my life unfun). If I edit the new combined latexdiff file to just remove the `DIFaddendFL`'s in front of \toprule it works fine.

**Comment by ftilmann** [comment]
@paul-pearce  if you don't use tabu, it is probably not the same issue. If you can post an example (ideally in the form of a minimum working example) that would be helpful. I will probably not deal with it straightaway but here have been a number of tabular related issues ( e.g. #5 ), and when I get to finally try to tackle this, it is good to have an overview what issues people have been encountering, and hopefully find a general solution that deals with them all.  Otherwise I can only suggest using PICTURENV to exclude processing inside tabular environments to at least make files compilable, but I appreciate this is not really satisfactory.
