### ISSUE TITLE
LaTeX only?

### ISSUE THREAD

**Issue by buhtz** [ftilmann/latexdiff#86]
Does latexdiff support only LaTeX or other TeX-engines/dialects (like XeTeX with unicode coded tex-files), too?

For me it looks like that there are problems with XeTeX code. But I am not sure.

Please specifice that in your help files an README.md to make it more cleare to the user.

Just an example error message:

```
WARNING: Inconsistency in length of input string and parsed string:
     This often indicates faulty or non-standard latex code.
     In many cases you can ignore this and the following warning messages.
 Note that character numbers in the following are counted beginning after \begin{document} and are only approximate.
tler(inne)n aus Deutschland, Österreich und der deutschsprachigen Schw

```

**Comment by ftilmann** [comment]
There are really two different issues in your question. Let me deal first with the compatibility issue.
latexdiff only supports latex source files, not generic TeX, or other versions of TeX. The README file only ever mentions latex input files, as does the README.md . In my view, there is not enough space in the README.md to specify what the code does _not_ do.  In the documentation, the behaviour with respect to TeX commands is mentioned explicitly:
>  If both old.tex and new.tex are valid LaTeX, then the resulting diff.tex
should also be valid LateX. (NB If a few plain TeX commands are used
within old.tex or new.tex then diff.tex is not guaranteed to work but
usually will).  There are even a few further restrictions placed on the latex file 

So I think the current documentation is clear enough. If you disagree and have specific suggestions for how to change the documentation, please provide them as a pull request or simple patch/diff listing.

**Comment by ftilmann** [comment]
To the second issue:
Unicode input should normally work OK, though you might see a few messages as you showed above.
These messages are not error messages, they are warning messages and most of the time, the resulting diff'ed tex file should be correct. Use option `--ignore-warnings` if they annoy you (but of course this makes potential failures harder to track down). In case the result does not work (and the reason is not that raw TeX commands have been used), feel free to report this as a bug by raising a new issue.

**Comment by buhtz** [comment]
"latex input files" are synonmy for all tex-dialects. It is not specific enough and will cause wrong expectations. The correct and technical meaning doesn't matter. Only what the users understand will matter. This is called useability what is a part of ergonimic.

Your README.md has not enough space? There is only one line in it. ;)

Code isn't documentation. I won't discusse that here. Attitudes like that damage the image of FOSS community.
Please keep the (none-developer) user in mind and the goals of the FOSS movement.

**Comment by ftilmann** [comment]
OK, the concise README.md file is a hold-over from CTAN, which I still consider to be the official release channel for latexdiff, where a one-liner description is strongly encouraged. Because the README.md is shown on the project main page, I would still prefer to keep it to one line.  I have always understood latex input files to refer to files suitable for input to (pdf|xe|...)latex (as opposed to generic TeX files suitable for (pdf|xe|..)tex varieties. I have certainly successfully used latexdiff with xelatex input files.   In my experience hardly anyone uses pure TeX files for actual documents. Sometimes a few TeX commands in a mostly latex source cause problems - technically it would be very difficult to address this unfortunately, but DIFnomarkup environment can be used to mitigate this shortcoming to some extent (see help pages)
If you think it is helpful I can emphasize the limitation to latex files in the README file. 

I am not sure what you mean by "Code isn't documentation". Nowhere in my answer do I refer to code, just the extended documentation provided as a pdf file (based on a .tex source).

**Comment by buhtz** [comment]
Then I just missunderstood you about the "Code isn't documention" thing. Sorry. ;)
I read this to often and it triggers my "red button". ;) Peace!

It would really help, save time and prevent frustration if there would be more specific and explicite informations about the supported and not supported tex-dialects. This is a problem for a lot of tex-docs and drives me cracy.

**Comment by ftilmann** [comment]
I have added the following to the README file: 'Note that only files conforming to latex syntax will 
be processed correctly, not generic TeX files. Some further minor restrictions apply, see documentation.' 
(not yet uploaded to github).  Hopefully this should make things clearer. Otherwise, please be very specific in your suggestion (i.e. suggest actual text to be added or changed).
