### ISSUE TITLE
Erroneous output if space occur between \cite and {

### ISSUE THREAD

**Issue by paul-pearce** [ftilmann/latexdiff#88]
Hello,

Old:
```
Text~\cite {citation} more text
```

New:
```
Text~\cite{citation} more text
```

Output:
```
Text~\DIFdelbegin \DIFdel{\mbox{%DIFAUXCMD
 \cite }%DIFAUXCMD
 }%DIFDELCMD < {%%%
 \DIFdel{citation}%DIFDELCMD < }
 %DIFDELCMD < %%%
 \DIFdel{more text }\DIFdelend \DIFaddbegin \DIFadd{\mbox{%DIFAUXCMD
 \cite{citation}
 }%DIFAUXCMD
more text }\DIFaddend
```

Which is invalid latex and will not compile. Clearly The syntax in Old is not good, but it does build, so it would be great if latexdiff handled it. (I only advocate for fixing this as I have this buried in a repo, and I can't clean up the hygiene without breaking latexdiff)

**Comment by ftilmann** [comment]
This is an important limitation of latexdiff that no spaces are allowed between a command and its arguments (otherwise latexdiff would need to know how many arguments each command takes, which would make this a whole different ballgame). It is documented in the manual but I appreciate it can sometimes not be avoided when working with coauthors or existing repositories. Try option `--allow-spaces`. It can have undesirable side effects, and in your case will possibly result in unjustified markup, but hopefully it should compile.
