### ISSUE TITLE
make install fails for git version

### ISSUE THREAD

**Issue by ouboub** [ftilmann/latexdiff#96]
Hi 

I followed the advice and pulled that latest github version. 
According to the REAME file I should run 

 make install

or sudo make install  but I obtain 

make: *** No rule to make target `install'.  Stop.

so I copied makefile to Mkaefile.s and Makefile.dist to Makefile
however 

sudo make install 

returned 
if [ -e /usr/local/bin/latexdiff ]; then rm /usr/local/bin/latexdiff; fi
install latexdiff-so /usr/local/bin
install: cannot stat ‘latexdiff-so’: No such file or directory
make: *** [install-latexdiff-so] Error 1

so i am stuck. I recommend to actualize the README file.

thanks

Uwe Brauer

**Comment by ftilmann** [comment]
I have to admit this is confusing, mostly due to historical reasons. The README is meant for the release (as part of the procedure of preparing releases, it is copied into the release folder), so it cannot be followed directly. My advice would really be to copy the github clone latexdiff and latexdiff-vc into your (user) bin folder rather than install it system-wide, so that you can fall back to release version in case some unreleased update breaks anything. On my computer I actually have symbolic links for latexdiff and latexdiff-vc from my bin directory into the live github clone, so that I am almost running the very latest latexdiff without the need to remember to copy updates into bin directory. If for some reason you cannot run plain latexdiff and need to run latexdiff-so or latexdiff-fast (which are generated automatically from latexdiff) you can generate a temporary release:

`
make distribution
`
This will generate a directory dist. You can cd into that directory and then follow the README and run 
`
make install
`
(note that the version number for such in-between releases is not unique; if you want to identify latexdiff unambiguously you would have to give the hash of the latest commit).

**Comment by ftilmann** [comment]
Note that I have renamed the README file to avoid confusion (commit d5ef1ae )

**Comment by ouboub** [comment]
Thanks, but wouldn't it be better also provide a README file for the github version README github?
Without your explanations I would not be able to use the github version, if say I pull it in 4 month again and have already forgotten your reply.

I suggest to say something like,

run make distribution (on you own risk), then enter the corresponding directory and proceed as indicated.

or something like this. 

I also would like to propose a new feature which would come in handy. I will open a new issue for that.

**Comment by ftilmann** [comment]
Yes, I will eventually do something like this although I don't think it crops up that often. Your newly opened issue #98 will remind me of that, so I will leave this issue closed.
